// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhMZ51tdahucXyjRZdyr61nGpXbINHn-Y',
    appId: '1:487581279668:web:f5823f254e92b4c21cfee1',
    messagingSenderId: '487581279668',
    projectId: 'devworld-socialmedia-app',
    authDomain: 'devworld-socialmedia-app.firebaseapp.com',
    storageBucket: 'devworld-socialmedia-app.appspot.com',
    measurementId: 'G-TZ900H7S4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBSjw979buZ-4CbIPSB12Cp2H6Cdiri2E',
    appId: '1:487581279668:android:ecec0faf66deef191cfee1',
    messagingSenderId: '487581279668',
    projectId: 'devworld-socialmedia-app',
    storageBucket: 'devworld-socialmedia-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH06ryZir4HUm_injKx2xxfnMeOxapbyo',
    appId: '1:487581279668:ios:149f6a26fa0aab241cfee1',
    messagingSenderId: '487581279668',
    projectId: 'devworld-socialmedia-app',
    storageBucket: 'devworld-socialmedia-app.appspot.com',
    iosClientId: '487581279668-n2spp47fm4ncir01tleitv1qep31gljf.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH06ryZir4HUm_injKx2xxfnMeOxapbyo',
    appId: '1:487581279668:ios:d76b1380b5632f351cfee1',
    messagingSenderId: '487581279668',
    projectId: 'devworld-socialmedia-app',
    storageBucket: 'devworld-socialmedia-app.appspot.com',
    iosClientId: '487581279668-1d62ck2lialroihutsqvae6ev1ch7cui.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
